### API: https://www.trafiklab.se/api/trafiklab-apis/sl/
### Skogslöparvägen = 300103715
### Centralen = 300109001
### Brommaplan = 300109109
### Spånga station = 301109704

### Transport authorities
https://transport.integration.sl.se/v1/transport-authorities

### A list of all lines
https://transport.integration.sl.se/v1/lines?transport_authority_id=1

### sites
https://transport.integration.sl.se/v1/sites?expand=false

### Stops
https://transport.integration.sl.se/v1/stop-points

### Sök efter stop - Skogslöparvägen
https://journeyplanner.integration.sl.se/v1/typeahead.json?searchstring=skogslöparvägen&stationsonly=true&maxresults=10&key=TRAFIKLAB-SLAPI-INTEGRATION-2024
### Sök efter stop - centralen
https://journeyplanner.integration.sl.se/v1/typeahead.json?searchstring=spånga&stationsonly=true&maxresults=10&key=TRAFIKLAB-SLAPI-INTEGRATION-2024

### Site id = 300103715 skogslöparvägen, man verkar skall använda 4 sista siffror
https://transport.integration.sl.se/v1/sites/3715/departures
### From Sls web
https://services.c.web.sl.se/departurewebservice/departures/site/9091001000003715

### Avvikelser ange fler parametrar
https://deviations.integration.sl.se/v1/messages?future=true

### Route ange fler parametrar
https://journeyplanner.integration.sl.se/v1/TravelplannerV3_1/trip.json?key=TRAFIKLAB-SLAPI-INTEGRATION-2024&originExtId=300103715&destExtId=300109001
### Via Spånga
https://journeyplanner.integration.sl.se/v1/TravelplannerV3_1/trip.json?key=TRAFIKLAB-SLAPI-INTEGRATION-2024&originExtId=300103715&destExtId=300109001&via=301109704

### Nearby stops, exemple
https://journeyplanner.integration.sl.se/v1/nearbystopsv2.json?originCoordLat=59.3646686&originCoordLong=17.9251941&key=TRAFIKLAB-SLAPI-INTEGRATION-2024